lab2

diff --git a/Lab2/poornames b/Lab2/poornames
--- a/Lab2/poornames
+++ b/Lab2/poornames
@@ -6,31 +6,33 @@ then
     path="$1"
 fi
 
+pathcheck=`echo $path | grep -E '^[^-]'`
 if [ ! -z "$2" ]
 then
     echo 'ERROR: too many arguments' 1>&2
     exit 1
-elif [ ! -d "$1" ]
-then
-    echo 'ERROR: not a directory' 1>&2
-    exit 1
-elif [[ $path =~ ^- ]]
+elif [ -z "$pathcheck" ]
 then
     echo "ERROR: argument cannot start with '-'" 1>&2
     exit 1
+elif [ ! -d "$path" ]
+then
+    echo 'ERROR: not a directory' 1>&2
+    exit 1
 fi
 
-last=`echo $1 | grep -E '/[A-za-z_]{1}[A-za-z.-_]{,13}$'`
-if [ -z "$last" ]
+lastcomp=`echo $path | grep -E '/[A-za-z_]{1}[A-za-z._-]{,13}$'`
+if [ -z "$lastcomp" ]
 then
-    echo "$1"
+    echo "$path"
     exit 0
 fi
 
 findpoor()
 {
     files=`ls $1`
-    dupl=`ls $1 | grep -E '^[A-za-z_]{1}[A-za-z.-_]{,13}$' | tr '[:upper:]' '[:lower:]' | sort | uniq -d`
+    dupl=`ls $1 | grep -E '^[A-za-z_]{1}[A-za-z._-]{,13}$' |
+ tr '[:upper:]' '[:lower:]' | sort | uniq -d`
     for s in $dupl
     do
         echo "$1/$s"
@@ -41,7 +43,7 @@ findpoor()
         then
             continue
         fi
-	namecheck=`echo $f | grep -E '^[A-za-z_]{1}[A-za-z.-_]{,13}$'`
+	namecheck=`echo $f | grep -E '^[A-za-z_]{1}[A-za-z._-]{,13}$'`
 	if [ -z $namecheck ]
 	then
 	    echo "$1/$f"
